[package]
name = "finance_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
csv = "1.3"
dirs = "5.0"
regex = "1.10"

[[bin]]
name = "fntr"
path = "src/main.rs"
test = true
